// Mock data for services - easily replaceable with API calls
export const SERVICES = [
  {
    id: 1,
    name: "Hair Cut & Color",
    category: "hair",
    price: 85,
    duration: 120,
    image: "/professional-hair-cut-styling.jpg",
    description: "Expert cuts and color treatments tailored to your style.",
  },
  {
    id: 2,
    name: "Hair Extensions",
    category: "hair",
    price: 250,
    duration: 180,
    image: "/luxury-hair-extensions.jpg",
    description: "Bellami, hand-tied wefts, micro-links, tape-ins for volume and length.",
  },
  {
    id: 3,
    name: "Ultra Conditioning Treatment",
    category: "hair",
    price: 200,
    duration: 60,
    image: "/professional-hair-treatment-ultrasound.jpg",
    description: "Advanced conditioning using ultrasound and infrared light technology.",
  },
  {
    id: 4,
    name: "Anti-Aging Facial",
    category: "skin",
    price: 120,
    duration: 60,
    image: "/luxury-facial-skincare-anti-aging.jpg",
    description: "Rejuvenating facial treatments to restore youthful radiance.",
  },
  {
    id: 5,
    name: "Acne-Clarifying Facial",
    category: "skin",
    price: 95,
    duration: 60,
    image: "/professional-facial-acne-treatment.jpg",
    description: "Targeted treatment for clear, healthy skin.",
  },
  {
    id: 6,
    name: "Massage Therapy",
    category: "wellness",
    price: 100,
    duration: 60,
    image: "/relaxing-spa-massage-therapy.jpg",
    description: "Therapeutic massage to relieve tension and promote relaxation.",
  },
  {
    id: 7,
    name: "Makeup Application",
    category: "makeup",
    price: 75,
    duration: 45,
    image: "/professional-makeup-artist-makeup.jpg",
    description: "Professional makeup for any occasion.",
  },
  {
    id: 8,
    name: "Manicure & Pedicure",
    category: "nails",
    price: 65,
    duration: 90,
    image: "/luxury-manicure-pedicure-nails.jpg",
    description: "Premium nail care with premium finishes.",
  },
]

export const TESTIMONIALS = [
  {
    id: 1,
    name: "Sarah Mitchell",
    text: "Senses Salon transformed my look completely. The stylists are true professionals who listen and exceed expectations.",
    rating: 5,
  },
  {
    id: 2,
    name: "Jennifer Chen",
    text: "The facials here are incredible. My skin has never looked better. Highly recommend!",
    rating: 5,
  },
  {
    id: 3,
    name: "Maria Rodriguez",
    text: "The hair extensions are flawless and the customer service is outstanding. Will be back!",
    rating: 5,
  },
]
